services:
  laocai:
    container_name: laocai
    image: laocai:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LLBOT_URL: http://host.docker.internal:3010
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "8080:8080"
