[project]
name = "laocai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "cryptography>=45.0.2",
    "fastapi[standard]",
    "openai>=1.81.0",
    "requests>=2.32.3",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true
