spring:
  application:
    name: laocai
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
    web-application-type: none
    keep-alive: true
laocai:
  bot:
    url: http://127.0.0.1:3010 # 如果不写，默认为 localhost:3010
    access-token: 123456
  dispatcher:
    concurrency: 32
    buffer-size: 5000