services:
  mysql:
    image: mysql:8.0.42
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456    # root 用户密码
      MYSQL_DATABASE: laocai_db                  # 初始化创建的数据库
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql:/var/lib/mysql         # 数据挂载
    restart: always
